School_0/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('info.urls')),
    path('info/', include('info.urls')),
    path('api/', include('apis.urls')),
    path('attendanceapp/', include('attendanceapp.urls')),
    path('accounts/login/',
         auth_views.LoginView.as_view(template_name='info/login.html'), name='login'),
    path('accounts/logout/',
         auth_views.LogoutView.as_view(template_name='info/logout.html'), name='logout'),
]

apis/urls.py
from django.urls import path, include
import apis.views as api_view
from django.contrib import admin


urlpatterns = [
    path('details/', api_view.DetailView.as_view()),
    path('attendance/', api_view.AttendanceView.as_view()),
    path('timetable/', api_view.TimetableView.as_view()),
]

info/urls.py
from django.urls import path, include
from . import views
from django.contrib import admin


urlpatterns = [
    path('', views.index, name='index'),
    path('student/<slug:stud_id>/attendance/',
         views.attendance, name='attendance'),
    path('student/<slug:stud_id>/<slug:course_id>/attendance/',
         views.attendance_detail, name='attendance_detail'),
    path('student/<slug:class_id>/timetable/',
         views.timetable, name='timetable'),
    path('add_student/',
         views.add_student, name='add_student'),
    path('add_teacher/',
         views.add_teacher, name='add_teacher'),     
    path('adminpage/',
          views.adminpage, name='adminpage'),
    path('logpage/',
          views.logpage, name='logpage'),
    path('system/',
          views.system_run, name='system_run'),     

    path('teacher/<slug:teacher_id>/<int:choice>/Classes/',
         views.t_clas, name='t_clas'),
    path('teacher/<int:assign_id>/Students/attendance/',
         views.t_student, name='t_student'),
    path('teacher/<int:assign_id>/ClassDates/',
         views.t_class_date, name='t_class_date'),
    path('teacher/<int:ass_c_id>/Cancel/',
         views.cancel_class, name='cancel_class'),
    path('teacher/<int:ass_c_id>/attendance/',
         views.t_attendance, name='t_attendance'),
    path('teacher/<int:ass_c_id>/Edit_att/', views.edit_att, name='edit_att'),
    path('teacher/<int:ass_c_id>/attendance/confirm/',
         views.confirm, name='confirm'),
    path('teacher/<slug:stud_id>/<slug:course_id>/attendance/',
         views.t_attendance_detail, name='t_attendance_detail'),
    path('teacher/<int:att_id>/change_attendance/',
         views.change_att, name='change_att'),
    path('teacher/<int:assign_id>/Extra_class/',
         views.t_extra_class, name='t_extra_class'),
    path('teacher/<slug:assign_id>/Extra_class/confirm/',
         views.e_confirm, name='e_confirm'),
    path('teacher/<int:assign_id>/Report/', views.t_report, name='t_report'),


    path('teacher/<slug:teacher_id>/t_timetable/',
         views.t_timetable, name='t_timetable'),
    path('teacher/<int:asst_id>/Free_teachers/',
         views.free_teachers, name='free_teachers'),


    path('api/auth/', include('djoser.urls')),
    path('admin/', admin.site.urls, name='admin'),
]
admin.site.site_url = None
admin.site.site_header = 'ADMİN LOGİN'

info/models.py
from django.db import models
import math
from django.contrib.auth.models import AbstractUser
from django.db.models.signals import *
from datetime import *





# Create your models here.


sex_choice = (
    ('Male', 'Male'),
    ('Female', 'Female')
)

time_slots = (
    ('7:30 - 8:30', '7:30 - 8:30'),
    ('8:30 - 9:30', '8:30 - 9:30'),
    ('9:30 - 10:30', '9:30 - 10:30'),
    ('11:00 - 11:50', '11:00 - 11:50'),
    ('11:50 - 12:40', '11:50 - 12:40'),
    ('12:40 - 1:30', '12:40 - 1:30'),
    ('2:30 - 3:30', '2:30 - 3:30'),
    ('3:30 - 4:30', '3:30 - 4:30'),
    ('4:30 - 5:30', '4:30 - 5:30'),
)

DAYS_OF_WEEK = (
    ('Pazartesi', 'Pazartesi'),
    ('Salı', 'Salı'),
    ('Çarşamba', 'Çarşamba'),
    ('Perşembe', 'Perşembe'),
    ('Cuma', 'Cuma'),
    ('Cumartesi', 'Cumartesi'),
)


class User(AbstractUser):
    @property
    def is_student(self):
        if hasattr(self, 'student'):
            return True
        return False

    @property
    def is_teacher(self):
        if hasattr(self, 'teacher'):
            return True
        return False


class Dept(models.Model):
    id = models.CharField(primary_key='True', max_length=100)
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name


class Course(models.Model):
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    id = models.CharField(primary_key='True', max_length=50)
    name = models.CharField(max_length=50)
    shortname = models.CharField(max_length=50, default='X')

    def __str__(self):
        return self.name


class Class(models.Model):
    # courses = models.ManyToManyField(Course, default=1)
    id = models.CharField(primary_key='True', max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE)
    section = models.CharField(max_length=100)
    sem = models.IntegerField()

    class Meta:
        verbose_name_plural = 'classes'

    def __str__(self):
        d = Dept.objects.get(name=self.dept)
        return '%s : %d %s' % (d.name, self.sem, self.section)


class Student(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE, default=1)
    usn = models.CharField(primary_key='True', max_length=100)
    name = models.CharField(max_length=200)
    sex = models.CharField(max_length=50, choices=sex_choice, default='Male')
    dob = models.DateField(default='1998-01-01')

    def _str_(self):
        return '%s : %s' % (self.usn, self.name)

class StudentCards(models.Model):
    usn = models.ForeignKey(Student, on_delete=models.CASCADE, null=True)
    name = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    rf_id = models.CharField(max_length=30, unique=True)

    def __str__(self):
        return str(self.name)+str(self.lastname)+ ' : ' + str(self.rf_id)



class Teacher(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, null=True)
    id = models.CharField(primary_key=True, max_length=100)
    dept = models.ForeignKey(Dept, on_delete=models.CASCADE, default=1)
    name = models.CharField(max_length=100)
    sex = models.CharField(max_length=50, choices=sex_choice, default='Male')
    dob = models.DateField(default='1980-01-01')

    def __str__(self):
        return self.name

class TeacherCards(models.Model):
    assing_id = models.CharField(max_length=100, unique=True)
    name = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    rf_id = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return str(self.name)+str(self.lastname)+ ' : ' + str(self.rf_id)

class Assign(models.Model):
    class_id = models.ForeignKey(Class, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    teacher = models.ForeignKey(Teacher, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('course', 'class_id', 'teacher'),)

    def __str__(self):
        cl = Class.objects.get(id=self.class_id_id)
        cr = Course.objects.get(id=self.course_id)
        te = Teacher.objects.get(id=self.teacher_id)
        return '%s : %s : %s' % (te.name, cr.shortname, cl)


class AssignTime(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    period = models.CharField(max_length=50, choices=time_slots, default='11:00 - 11:50')
    day = models.CharField(max_length=15, choices=DAYS_OF_WEEK)





class AttendanceClass(models.Model):
    assign = models.ForeignKey(Assign, on_delete=models.CASCADE)
    date = models.CharField(default='2018-10-23 11', max_length=13)
    status = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Attendance'
        verbose_name_plural = 'Attendance'


class Attendance(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    attendanceclass = models.ForeignKey(AttendanceClass, on_delete=models.CASCADE, default=1)
    date = models.CharField(default='2018-10-23 11', max_length=100)
    status = models.BooleanField(default='True')

    def __str__(self):
        usn = self.student.usn
        name = self.student.name
        cname = self.course.id
        return '%s : %s : %s : %s: %s' % (usn, name, self.date, cname, self.status)


class AttendanceTotal(models.Model):
    course = models.ForeignKey(Course, on_delete=models.CASCADE)
    student = models.ForeignKey(Student, on_delete=models.CASCADE)

    class Meta:
        unique_together = (('student', 'course'),)

    @property
    def att_class(self):
        stud = self.student
        cr = Course.objects.get(name=self.course)
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        return att_class

    @property
    def total_class(self):
        stud = self.student
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        return total_class

    @property
    def attendance(self):
        stud = self.student
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        if total_class == 0:
            attendance = 0
        else:
            attendance = round(att_class / total_class * 100, 2)
        return attendance

    @property
    def classes_to_attend(self):
        stud = self.student
        cr = Course.objects.get(name=self.course)
        total_class = Attendance.objects.filter(course=cr, student=stud).count()
        att_class = Attendance.objects.filter(course=cr, student=stud, status='True').count()
        cta = math.ceil((0.70 * total_class - att_class) / 0.30)
        if cta < 0:
            return 0
        return cta
    
    def __str__(self):
        return '%s : %s : %s : %s' % (self.student.usn, self.student.name, self.course.name, self.attendance)
    


class StudentCourse(models.Model):
    student = models.ForeignKey(Student, on_delete=models.CASCADE)
    course = models.ForeignKey(Course, on_delete=models.CASCADE)

    def __str__(self):
        name=self.student.name
        usn=self.student.usn
        course=self.course.id
        course_name = self.course.name
        return '%s : %s : %s : %s ' % (usn, name, course, course_name)
    
    def get_attendance(self):
        a = AttendanceTotal.objects.get(student=self.student, course=self.course)
        return a.attendance


class AttendanceRange(models.Model):
    range_classid = models.CharField(max_length=30)
    start_date = models.CharField(max_length=100)
    end_date = models.CharField(max_length=100 )

class Log(models.Model):
    card_id = models.CharField(max_length=100)
    time_in = models.CharField(max_length=100)
    status_at = models.BooleanField(default='True')
    invalid_entry = models.BooleanField(default='True')
    face_data = models.CharField(max_length=250000) 

    def __str__(self):
        return str(self.card_id) + ' : ' + str(self.time_in)





# Django signals


def daterange(start_date, end_date):
    int_time=int(((end_date - start_date).days)/7)
    rng = range(int_time)
    for n in rng:
        yield start_date + timedelta(days=n*7)


days = {
    'Pazartesi': 1,
    'Salı': 2,
    'Çarşamba': 3,
    'Perşembe': 4,
    'Cuma': 5,
    'Cumartesi': 6,
}


def create_attendance(sender, instance, **kwargs):
    if kwargs['created']:
        start_date = AttendanceRange.objects.all()[:1].get().start_date
        start_date = start_date[:13]

        end_date = AttendanceRange.objects.all()[:1].get().end_date
        end_date = end_date[:13]

        s = datetime.strptime(start_date,"%Y-%m-%d %H")
        e = datetime.strptime(end_date,"%Y-%m-%d %H")
        
        # bu kısımı Daha sonra logtaki time in ile netegre etmek için di çok gerekli değil artık.
        # l_time = Log.objects.order_by('-id').all()[:1].get().time_in
        # log_t = l_time[:10]
        # l = datetime.strptime(log_t,"%Y-%m-%d")

        
        for single_date in daterange(s, e):
            try:
                AttendanceClass.objects.get(date=str(single_date)[:13], assign=instance.assign)
            except AttendanceClass.DoesNotExist:
                a = AttendanceClass(date=str(single_date)[:13], assign=instance.assign)
                a.save()




# def insert_attendance(sender, instance, **kwargs):
#     if kwargs['created']:
#         start_date = AttendanceRange.objects.all()[:1].get().start_date
#         end_date = AttendanceRange.objects.all()[:1].get().end_date
#         log_time= Log.objects.order_by('-id').all()[:1].get().time_in
#         RF_id= Log.objects.order_by('-id').all()[:1].get().card_id
#         master_rfid=TeacherCards.objects.get(rf_id=RF_id).rf_id

info/templates/info/Log_page.html
<!DOCTYPE html>
<html lang="en">
 
    <head>

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>Ana sayfa</title>
        {% load static %}
        {% csrf_token %}
        <!-- Bootstrap core CSS -->
        <link href="{% static '/info/homepage/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


        <!-- Custom styles for this template -->
        <link href="{% static '/info/homepage/css/heroic-features.css' %}" rel="stylesheet">
            <link href="{% static '/info/bootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">



    </head>
    <body>
      <!-- Navigation -->
      <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
        <div class="container">
          <a class="navbar-brand" href="{% url 'index' %}">Esogü</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item">
                  <a class="nav-link" href="#" data-toggle="modal" data-target="#logoutModal">Çıkış</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>

      <div class="container">
        
        <!-- Jumbotron Header -->
        <header class="jumbotron my-4">
          <h1 class="display-2 text-capitalize text-center">Kayıt Tablosu</h1>
          
        </header>
        <header class="jumbotron my-4 ">
          <h2 class="display-8 text-capitalize">Yetkisiz Kayıtlar</h2>
          <table class="table table-bordered text-center" id="data2Table" width="100%" cellspacing="0">
            
              <thead class="bg-white" >
                <tr>
                  <th>Yetkisiz</th>
                  
                </tr>
              </thead>
              <tbody>
                  <tr>
                    {% if count != 0 %}
                        <td class=" display-4 p-3 mb-2 bg-danger text-white">{{ count }}</td>
                    {% else %}    
                        <td class=" display-4 p-3 mb-2 bg-success text-white">Herhangi bir yetkisiz kayıt yoktur.</td>
                    {% endif %}
                  </tr>
              </tbody>
          </table>
        </header>
        {% block content %}
          
        <div class="card-body">
            <div class="table-responsive">
              <table class="table table-bordered text-center" id="dataTable" width="100%" cellspacing="0">
                <thead class="thead-light ">
                  <tr>
                      <th>ID</th>
                      <th>Kart ID</th>
                      <th>Girdi Zamanı</th>
                      <th>Durum</th>
                      <th>Yetki</th>
                      <th>Resim</th>
                  </tr>
                </thead>
                <tbody class="bg-white">
                  {% for a in log_list %}
                  <tr>
                      <td>{{ a.id }}</td>
                      <td>{{a.card_id}}</a></td>
                      <td>{{ a.time_in }}</td>
                      {% if a.status_at == 0 %}
                          <td class="p-3 mb-2 bg-danger text-white">{{ a.status_at }}</td>
                      {% elif a.status_at == 1 %}
                          <td class="p-3 mb-2 bg-success text-white">{{ a.status_at }}</td>
                      {% else %} 
                          <td class="p-3 mb-2 bg-warning text-white">{{ a.status_at }}</td>
                      {% endif %}
                      {% if a.invalid_entry == 0 %}
                          <td class="p-3 mb-2 bg-danger text-white">{{ a.invalid_entry }}</td>
                      {% elif a.invalid_entry == 1  %}
                          <td class="p-3 mb-2 bg-success text-white">{{ a.invalid_entry }}</td>
                      {% else %}    
                          <td class="p-3 mb-2 bg-warning text-white">{{ a.invalid_entry }}</td>
                      {% endif %}
                        <td><img style='display:block; width:100px;height:100px;' id='base64image'
                        src='data:image/jpg;base64,{{a.face_data}}'></td>
                        
                      
                  </tr>
                  {% empty %}
                  <h3 class="p-3 mb-2 bg-warning text-white">Herhangi bir kayıt yoktur.</h3>
                  <tr>
                    <td></td>
                  </tr>
                          
                  {% endfor %}

                </tbody>
              </table>
            </div>
          </div>
        
        {% endblock %}
      </div>
    </body>
    
</html> 

info/templates/info/add_teacher.html
<!DOCTYPE html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Ana sayfa</title>
      {% load static %}

    <!-- Bootstrap core CSS -->
      <link href="{% static '/info/homepage/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">


    <!-- Custom styles for this template -->
      <link href="{% static '/info/homepage/css/heroic-features.css' %}" rel="stylesheet">
          <link href="{% static '/info/bootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">



  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
      <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Esogü</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
                <a class="nav-link" href="#" data-toggle="modal" data-target="#logoutModal">Çıkış</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>

    <!-- Page Content -->
    <div class="container">

      <!-- Jumbotron Header -->
      <header class="jumbotron my-4">
        <h1 class="display-3 text-capitalize">Hoşgeldiniz {{ request.user }}</h1>
      </header>

      <!-- Page Features -->
      <div class="row text-center justify-content-center">
        <div class="row justify-content-center">
            <div class="">
              <span class="anchor" id="formUserEdit"></span>
              <hr class="my-5">
              <div class="card card-outline-secondary" style="min-width: 600px;">
                <div class="card-header">
                  <h3 class="mb-0">Fakülte Bilgileri</h3>
                </div>
                <div class="card-body">
                  <form class="form" role="form" method="POST" action="{% url 'add_teacher' %}">
                        {% csrf_token %}
                        <div class="form-group row">
                        <label class="col-lg-3 col-form-label form-control-label">ID</label>
                        <div class="col-lg-9">
                            <input class="form-control" name="id" type="text" placeholder="CS04" required>
                        </div>
                        </div>
                        <div class="form-group row">
                        <label class="col-lg-3 col-form-label form-control-label">Tam İsim</label>
                        <div class="col-lg-9">
                            <input class="form-control" type="text" name="full_name" placeholder="Bilginer Gülmezoğlu" required>
                        </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">Bölüm</label>
                            <div class="col-lg-9">
                            <select class="form-control" name="dept" required>
                                    {% for dept in all_dept %}
                                        <option value="{{ dept.id }}">
                                            {{ dept }}
                                        </option>
                                    {% endfor %}
                            </select>
                            </div>
                        </div>
                        <div class="form-group row">
                            <label class="col-lg-3 col-form-label form-control-label">Cinsiyet</label>
                            <div class="col-lg-9">
                            <select class="form-control" name="sex" required>
                                <option value="Male">
                                    Erkek
                                </option>
                                <option value="Female">
                                    Kadın
                                </option>
                            </select>
                            </div>
                        </div>
                        <div class="form-group row">
                        <label class="col-lg-3 col-form-label form-control-label">Doğum Tarihi</label>
                            <div class="col-lg-9">
                                <input class="form-control" name="dob" type="date" required>
                            </div>
                        </div>


                    <div class="form-group row justify-content-left">
                        <div class="ml-auto mr-3">
                            <a class="btn btn-danger" href="{% url 'index' %}"> İptal </a>
                            <input class="btn btn-secondary ml-auto" type="reset" value="Reset">
                            <input class="btn btn-primary ml-auto" type="submit" value="Submit">
                        </div>
                    </div>
                  </form>
                </div>
              </div>
            </div>
          </div>

      </div>
      <!-- /.row -->

    </div>
    <!-- /.container -->
    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Ayrılmak istediğinizden emin misiniz?</h5>
            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">×</span>
            </button>
          </div>
          <div class="modal-body">Mevcut oturumunuzu bitirmeye hazırsanız, aşağıdan "Çıkış"ı seçin.</div>
          <div class="modal-footer">
            <button class="btn btn-secondary" type="button" data-dismiss="modal">İptal</button>
            <a class="btn btn-primary" href="/accounts/logout">Çıkış</a>
          </div>
        </div>
      </div>
    </div>

    <!-- Bootstrap core JavaScript -->


      <script src="{% static '/info/homepage/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static '/info/homepage/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  </body>

</html>

info/templates/info/att_detail.html
{% extends 'info/base.html' %}

    {% block content %}
        <div class="card mb-3">
            <div class="card-header">
              <i class="fas fa-table"></i>
            <strong>{{ cr.name }}</strong></div>
            <div class="card-body">
              <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                  <thead>
                    <tr>
                        <th>#</th>
                        <th>Tarih</th>
                        
                        <th>Durum</th>
                        <th></th>
                    </tr>
                  </thead>
                  <tbody>
                        {% for a in att_list %}
                        <tr class="row100 body">
                            <td>{{ forloop.counter }}</td>
                            <td>{{ a.date }}</td>
                            
                            {% if a.status %}
                            <td class="p-3 mb-2 bg-success text-white">Mevcut <span class="glyphicon glyphicon-thumbs-up"></span></td>
                            {% else %}
                            <td class="p-3 mb-2 bg-danger text-white">Yok <span class="glyphicon glyphicon-thumbs-down"></span</td>
                            {% endif %}
                        </tr>
                    {% empty %}
                            <p>Yoklama bilgisi yoktur.</p>
                    {% endfor %}

                  </tbody>
                </table>
              </div>
            </div>
          </div>


    {% endblock %}

info/templates/info/free_teachers.html
{% load static %}

<!-- Bootstrap core CSS-->
<link href="{% static '/info/bootstrap/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- Custom fonts for this template-->
<link href="{% static '/info/bootstrap/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <h2 class="text-center">Diğer Öğretmenlerin Listesi</h2>
    <ul class="list-group">
        {% for t in ft_list %}
            <li class="list-group-item list-group-item-success">{{ t }}</li>
        {% endfor %}
    </ul>

info/templates/info/t_attendance.html
{% extends 'info/base.html' %}
{% block content %}
{% if c.student_set.all %}

<form action="{% url 'confirm' assc.id %}" method="post">
            {% csrf_token %}
    <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
         <b>{{ dept1.name }}</b></div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                    <th>Öğrenci Adı</th>
                    <th></th>
                </tr>
              </thead>
                <tbody>
                {% for s in c.student_set.all %}
                    <tr>
                    <td>{{s.name}}</td>
                    <td>
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">

                                <label class="btn btn-outline-success active">
                                    <input type="radio" name="{{ s.usn }}" id="option1" autocomplete="off" value="present" checked> Mevcut
                                </label>

                                <label class="btn btn-outline-danger">
                                    <input type="radio" name="{{ s.usn }}" id="option2" autocomplete="off" value="absent"> Yok
                                </label>
                        </div>
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
      </div>


    <input class="btn btn-success" type="submit" value="Submit">
</form>


{% else %}
    <p>Sınıfta Öğrenci Yok</p>
{% endif %}

{% endblock %}

info/templates/info/t_extra_class.html
{% extends 'info/base.html' %}
{% block content %}
{% if c.student_set.all %}

<form action="{% url 'e_confirm' ass.id %}" method="post">
            {% csrf_token %}
    <label for="date">Giriş Zamanı: </label>
    <input type="date" name="date">


    <div class="card mb-3">
        <div class="card-header">
          <i class="fas fa-table"></i>
         <b>{{ dept1.name }}</b></div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                    <th>Öğrenci İsmi</th>
                    <th></th>
                </tr>
              </thead>
                <tbody>
                {% for s in c.student_set.all %}
                    <tr>
                    <td>{{s.name}}</td>
                    <td>
                        <div class="btn-group btn-group-toggle" data-toggle="buttons">

                                <label class="btn btn-outline-success active">
                                    <input type="radio" name="{{ s.usn }}" id="option1" autocomplete="off" value="present" checked> Mevcut
                                </label>

                                <label class="btn btn-outline-danger">
                                    <input type="radio" name="{{ s.usn }}" id="option2" autocomplete="off" value="absent"> Yok
                                </label>
                        </div>
                    </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
          </div>
        </div>
      </div>


    <input class="btn btn-success" type="submit" value="Submit">
</form>


{% else %}
    <p>Sınıfta öğrenci yok.</p>
{% endif %}

{% endblock %}